# [black](black)
# [red](red)
# [green](green)
# [blue](blue)
# [yellow]( yellow)
# [purple]( purple)
# [cyan]( cyan)
# [white]( white)
#
# [black](bold black)
# [red](bold red)
# [green](bold green)
# [blue](bold blue)
# [yellow](bold yellow)
# [purple](bold purple)
# [cyan](bold cyan)
# [white](bold white)

format = """
╭╴$username$sudo$hostname$directory$git_branch$git_metrics$git_status$git_state $fill $all
╰╴$character
"""
# ─

[username]
show_always = true
format = '[$user]($style)'

[sudo]
symbol = '⚡'
format = ' [$symbol]($style)'
disabled = false

[hostname]
format = ' [$ssh_symbol$hostname](style)'

[directory]
format = ' in [$path]($style)'
truncation_symbol = '.../'


[line_break]
disabled = true

[fill]
symbol = ' '
style = 'none'

[git_branch]
format = ' on [$symbol$branch(:$remote_branch)]($style)'
[git_status]
format = '( [\[$all_status$ahead_behind\]]($style))'

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'

[git_metrics]
disabled = false
format = '( [+$added]($added_style))( [-$deleted]($deleted_style))'

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
